modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory (28 is current forge version)
issueTrackerURL="http://github.com/AtomicBlom/ShearMadness/issues" #optional
license="LGPL3"

[[mods]] #mandatory
    modId="shearmadness" #mandatory
    version="${file.jarVersion}" #mandatory
    displayName="Shear Madness" #mandatory
    # updateJSONURL="http://myurl.me/" #optional
    displayURL="http://github.com/AtomicBlom/ShearMadness" #optional
    logoFile="Logo.png" #optional
    credits="" #optional
    authors="AtomicBlom" #optional
    description="Sheep is confused and alarmed"

[[dependencies.shearmadness]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.shearmadness]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
